apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gromo.fullname" . }}-secrets
  labels:
    {{- include "gromo.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  twilio-account-sid: {{ .Values.secrets.twilioAccountSid | b64enc | quote }}
  twilio-auth-token: {{ .Values.secrets.twilioAuthToken | b64enc | quote }}
  twilio-phone-number: {{ .Values.secrets.twilioPhoneNumber | b64enc | quote }}
  twilio-whatsapp-number: {{ .Values.secrets.twilioWhatsappNumber | b64enc | quote }}
  {{- if .Values.externalMongodb.enabled }}
  mongodb-password: {{ .Values.externalMongodb.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalRedis.enabled }}
  redis-password: {{ .Values.externalRedis.password | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gromo.fullname" . }}-google-credentials
  labels:
    {{- include "gromo.labels" . | nindent 4 }}
type: Opaque
data:
  google-credentials.json: {{ .Values.secrets.googleApplicationCredentials | b64enc | quote }}
