apiVersion: v1
kind: ConfigMap
metadata:
  name: gromo-config
  namespace: gromo
data:
  NODE_ENV: "production"
  PORT: "3000"
  MONGODB_HOST: "mongodb-service"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "gromo"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  LOG_LEVEL: "info"
  MAX_FILE_SIZE: "50MB"
  SUPPORTED_FORMATS: "pdf,jpg,jpeg,png,tiff,bmp"
  TESSERACT_LANG: "eng+hin"
---
apiVersion: v1
kind: Secret
metadata:
  name: gromo-secrets
  namespace: gromo
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  MONGODB_USERNAME: "" # echo -n "username" | base64
  MONGODB_PASSWORD: "" # echo -n "password" | base64
  REDIS_PASSWORD: "" # echo -n "password" | base64
  JWT_SECRET: "" # echo -n "your-jwt-secret" | base64
  TWILIO_ACCOUNT_SID: "" # echo -n "your-twilio-sid" | base64
  TWILIO_AUTH_TOKEN: "" # echo -n "your-twilio-token" | base64
  TWILIO_PHONE_NUMBER: "" # echo -n "your-twilio-number" | base64
  TWILIO_WHATSAPP_NUMBER: "" # echo -n "whatsapp:+14155238886" | base64
  GOOGLE_APPLICATION_CREDENTIALS: "" # echo -n "/path/to/credentials.json" | base64
